# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

zstdCompressImpl <- function(data, level) {
    .Call('zstdr_zstdCompressImpl', PACKAGE = 'zstdr', data, level)
}

zstdDecompressImpl <- function(data) {
    .Call('zstdr_zstdDecompressImpl', PACKAGE = 'zstdr', data)
}

zstdMaxCLevelImpl <- function() {
    .Call('zstdr_zstdMaxCLevelImpl', PACKAGE = 'zstdr')
}

